/*
 * Copyright (C) 2025 cesarbianchi
 */
package com.lariflix.jemm.forms;

/**
 * Footer panel used by the Backdrop Image generator wizard.
 *
 * <p>This small Swing panel is intended to appear at the bottom of the
 * backdrop generation wizard and provides a consistent layout region for
 * navigation buttons or status text. The UI is generated by the Form Editor
 * and contains no dynamic logic.
 *
 * @author Cesar Bianchi
 * @since 1.0
 * @see BackdropGeneratorWizard
 */
public class BackdropWizardPanel_Footer extends javax.swing.JPanel {

    /**
     * Creates new form BackdropWizardPanel_Footer and initializes components.
     *
     * @since 1.0
     */
    public BackdropWizardPanel_Footer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
