package com.lariflix.jemm.forms;

/**
 * This class represents a panel that is displayed while the application is waiting for a process to complete.
 * It extends the JPanel class from the javax.swing package.
 * 
 * @author Cesar Bianchi
 * @since 1.0
 * @see javax.swing.JPanel
 */
public class WaitingPanel extends javax.swing.JPanel {

    private final int DOWNLOADING_DATA = 1;
    private final int UPLOADING_DATA = 2;
    private int SELECTED_OPTION = 0;
    private String cMessage = new String();
    private String baseURL = new String();
    
    /**
     * Constructs a new WaitingPanel with the specified base URL and option.
     * This constructor initializes the components of the panel, sets the base URL, and sets the option for downloading or uploading data.
     * 
     * @param cInsURL The base URL to be set.
     * @param nOption The option to be set. It can be either DOWNLOADING_DATA or UPLOADING_DATA.
     * @author Cesar Bianchi
     * @since 1.0
     */
    public WaitingPanel(String cInsURL, int nOption) {       
        initComponents();
        
        this.setBaseURL(cInsURL);
        if (nOption == DOWNLOADING_DATA){
            this.setOptionDowloading();
        } else if (nOption == UPLOADING_DATA){
            this.setOptionUploading();
        }
        
    }

    /**
     * Sets the selected option to DOWNLOADING_DATA and updates the message and label text accordingly.
     * This method sets the selected option to DOWNLOADING_DATA, constructs a message with the base URL, and sets this message as the text of jLabel2.
     * 
     * @author Cesar Bianchi
     * @since 1.0
     */
    public void setOptionDowloading() {
        this.SELECTED_OPTION = DOWNLOADING_DATA;
        this.setcMessage("Downloading data from ".concat(this.getBaseURL()));
        jLabel2.setText(this.getcMessage());
    }
    
    /**
     * Sets the selected option to DOWNLOADING_DATA and updates the message and label text accordingly.
     * This method sets the selected option to DOWNLOADING_DATA, constructs a message with the base URL, and sets this message as the text of jLabel2.
     * 
     * @author Cesar Bianchi
     * @since 1.0
     * @see #setcMessage(String)
     * @see #getBaseURL()
     * @see #getcMessage()
     */
    public void setOptionUploading() {
        this.SELECTED_OPTION = UPLOADING_DATA;
        this.setcMessage("Uploading data to ".concat(this.getBaseURL()));
        jLabel2.setText(this.getcMessage());
    }

    /**
     * Gets the base URL.
     * 
     * @return The base URL.
     * @author Cesar Bianchi
     * @since 1.0
     */
    public String getBaseURL() {
        return baseURL;
    }

    /**
     * Sets the base URL.
     * 
     * @param baseURL The base URL to be set.
     * @author Cesar Bianchi
     * @since 1.0
     */
    public void setBaseURL(String baseURL) {
        this.baseURL = baseURL;
    }

    /**
     * Gets the message.
     * 
     * @return The message.
     * @author Cesar Bianchi
     * @since 1.0
     */
    public String getcMessage() {
        return cMessage;
    }

    /**
     * Sets the message.
     * 
     * @param cMessage The message to be set.
     * @author Cesar Bianchi
     * @since 1.0
     */
    public void setcMessage(String cMessage) {
        this.cMessage = cMessage;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jellyfinIconTransparency_small.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Downloading data from ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}