site_name: JEMM - User Manual
site_description: Welcome to the Jellyfin Easy Metadata Manager Users Manual
site_author: Cesar Bianchi

theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

  analytics:
    gtag: G-ABC123
  locale: en

nav:
 - About:
   - What's Jemm ?: about/whatsjemm.md
   - Requirements: about/requirements.md
   - Download: about/download.md
   - Source Code: about/sourcecode.md
   - Author: about/theauthor.md
   - Found a Bug ?: about/bugs.md
   - Buy me a Coffee: about/donations.md
   - The Jellyfin Project: about/jellyfinproject.md
 - Features:
   - Login Process: feat/login.md
   - Main Menu: feat/mainmenu.md
   - The Top Menu: feat/topmainmenu.md
   - Library List: feat/librarylist.md
   - Library Metadata Sheet: feat/librarymetadata.md
   - Library Content Sheet: feat/librarycontent.md
   - Footer StatusBar: feat/footerStatusBar.md
   - Export Feature: feat/exportfeature.md
   - Import Feature: feat/importfeature.md
   - Reports: 
     - Inventory: feat/reportInventory.md
     - Genres: feat/reportGenres.md
     - People: feat/reportPeople.md
     - Studios: feat/reportStudios.md
     - Tags: feat/reportTags.md
     - Year: feat/reportYear.md